steps:
# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}', '.']
  id: Building the container image
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west2-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}']
  id: Pushing the image to registry
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_REPOSITORY}', '--image', 'us-west2-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:${SHORT_SHA}', '--region', 'us-west2', '--platform', 'managed', "--allow-unauthenticated"]

substitutions:
    #Repository Specific configuration. DevOps can change this settings
    _REPOSITORY: port-demo
    _IMAGE_NAME: $(body.payload.properties.image_name)
    
options:
    substitution_option: 'ALLOW_LOOSE'